var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                        o                                                       ",
   "                        x                                                       ",
   "                                                                                ",
   "                     o       o                                                  ",
   "                     o      xxx                                  xxxxx          ",
   "                     o                             xxx     xxx   x!!!x          ",
   "                     o                       xx    xvx     xyx   xxvxx          ",
   "                                    o  o                   xxx                  ",
   "                                    x  x                                        ",
   "                                                                                ",
   "                o                                                            x  ",
   "               xxx                          o                                x  ",
   "yy           o xyx                         xxx                             xxx  ",
   "xx           xxxxx                                                         y x  ",
   "x          o x      y               o                            xxxxx       x  ",
   "x@         xxxyyxxxxxxxxxxxxxxx     x    xxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxoo",
   "xx         x                  x          x           x     x                    ",
   "xx o  o  xxx                  x!!!!!!!!!!x           x!!!!!x                    ",
   "xxxx  xxxx                    x!!!!!!!!!!x           x!!!!!x                    ",
   "   x  x                       xxxxxxxxxxxx           xxxxxxx                    ",
   "   x  x                                                                      x  ",
   "   xyyx                                                                      xxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                                                                x",
   "x                                   oo                                                                           x",
   "x                                   xx                                                                           x",
   "x                               oo     oo            y                                                           x",
   "x                               xx     xx                                     o                                  x",
   "x                                                                     xxxxxxxxxx                                 x",
   "x                                                    o                x                                          x",
   "x                                                    x                x                                          x",
   "x                     xxxxxxxxxxxxxxxxxxxxxxxxxxxx   x   xxxxxxxxxxxxxxxxxxx x     o                             x",
   "x                  xxxx                          x!!!x!!!x                 xox     x                             x",
   "x   y   y   y     xx                             xxxxxxxxx                 x x  o               o       ooy      x",
   "x   x   x   x  o xx                                                        x x  x               x      xxxx      x",
   "x   v   v   v  x xx                                                        x x      o      o                     x",
   "x                                                                          x x      x      x                     x",
   "x                                                                          x x          o                        x",
   "x  yyy  yy                                      !   !!  !   !  ! !         x x          x                        x",
   "x x   x   x  x  x  x  x x x xxx                 !!  !   !  !!! ! !         xox!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "x v   v   v  v  v  v  v v v v v  o              ! ! !! ! !  !  !!!         x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "x                                x              !!  !  !!!  !  ! !         x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "x                                  o            !   !! ! !  !  ! !         x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "x                       x   x      x                                       x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "x                                                                          x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "x @                                                                        x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!!!!!!!!!!v!!!!!!!!!!!!!v!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!!!!!!!!!! !!!!!!!!!!!!! !!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                     o",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                         x                          x                                         ",
   "                                         x                          x                                         ",
   "                                         x   @             o  o     x                                         ",
   "                                         xxxxxxxxxxxxxxxxxxxxxx     x                                         ",
   "                                         x                          x                                         ",
   "                                         x     o   o                x                                         ",
   "                                         x    xxxxxxxxxxxxxxxxxxxxxxx                                         ",
   "                                                                    x                                         ",
   "    y      o       o       o       o                               ox                                         ",
   "    x      x       x       xx     xxx   xxxxxxxxxxxxxxxxxxxx        x                                         ",
   "                                         x                         xx                                         ",
   "                                         x                          x                                         ",
   "                                         x                                                                    ",
   "                                         x                                   o                                ",
   "                                         xxxxxxxx     xxxxxxxxxxxxxxxx      xxx                               ",
   "                                         x  y   x              y y  x                                         ",
   "                                         x  x   x              x x  x                                         ",
   "                                         x  v   x        y     v v  x                                         ",
   "                                         x      x     xxxxxxx       x                                         ",
   "                                         x      x  x  x  x  x       x                                         ",
   "                                         x      x  v  x  v  x       x                                         ",
   "                                         x      x     x     x       x                                         ",
   "                                         x      xxxxxxx     x       x                                         ",
   "                                         x                  x       x                                         ",
   "                                         x                  x       x                                         ",
   "                     o                   x     xxxxxx                                                         ",
   "                    xxx                  x     x    xx                      o o                               ",
   "                                         x     x    xxxxxxxxxxxxxxxxxx     xxxxx                              ",
   "                            o            x     x                    x                                         ",
   "                           xxx           x     x                    x                                         ",
   "                                                                    x                                         ",
   "                                 o                                  x                                         ",
   "                                xxx     xxxxxxxxx  xx   xxx         x                                         ",
   "                                         x      x!!!!!!!x           x                                         ",
   "                                         x      xxxxxxxxx           x                                         ",
   "                                         x                          x                                         ",
   "                                         x                     y    x                                         ",
   "                                         x    xxxxxxxxxxxxxxxxxxxxxxx                                         ",
   "                                         x                          x                                         ",
   "                                         x                          x                                         ",
   "                                         x                          x                                         ",
   "                                         x                          x                                         ",
   "                                         x                          x                                         ",
   "                                         x     o o o o o o o o o o ox                                         ",
   "                                         x    o o o o o o o o o o o x                                         ",
   "                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                     !   !  !!!!!  !   !    !    !  !  !   !    !!                                            ",
   "                      ! !   !   !  !   !    !    !  !  !!  !    !!                                            ",
   "                       !    !   !  !   !    ! !! !  !  ! ! !    !!                                            ",
   "                       !    !   !  !   !    ! !! !  !  !  !!                                                  ",
   "                       !    !!!!!  !!!!!     !  !   !  !   !    !!                                            ",
   "                @                                                                                             ",
   "                                                                       o                                      ",
   "              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                    ",
   "  x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                    ",
   "  x                                                                                                           ",
   "  xxxxxxx                                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
